@startebnf

file = {exp | ";"};

block = "(" , {exp | ";"} , ")";

exp = var | local-var | block;

var = word;
local-var = "@" , word;

word = word-start , {?anychar?};

word-start = ?uppercase-char? | ?non-alphabet-char?;

@endebnf