@startebnf

file = {exp | ";"};

block = "(" , {exp | ";"} , ")";

exp = var | local-var | block | number | string;

number = integer | decimal;
integer = {?0-9?}-;
decimal = {?0-9?}- , "." , {?0-9?}-;

string = '"' , {?anychar?}, " "  | '""' , {?anychar?} , '""';

var = word;
local-var = "@" , word;

word = word-start , {?anychar?};

word-start = ?uppercase-char? | ?non-alphabet-char?;

@endebnf